/* Auto-generated by genmsg_cpp for file /home/asfandyar/gnss-master/rtkrcv/msg/PreciseClock.msg */
#ifndef RTKRCV_MESSAGE_PRECISECLOCK_H
#define RTKRCV_MESSAGE_PRECISECLOCK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace rtkrcv
{
template <class ContainerAllocator>
struct PreciseClock_ {
  typedef PreciseClock_<ContainerAllocator> Type;

  PreciseClock_()
  : time()
  , index(0)
  , clk()
  , std()
  {
  }

  PreciseClock_(const ContainerAllocator& _alloc)
  : time()
  , index(0)
  , clk(_alloc)
  , std(_alloc)
  {
  }

  typedef ros::Time _time_type;
  ros::Time time;

  typedef int32_t _index_type;
  int32_t index;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _clk_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  clk;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _std_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  std;


  typedef boost::shared_ptr< ::rtkrcv::PreciseClock_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rtkrcv::PreciseClock_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PreciseClock
typedef  ::rtkrcv::PreciseClock_<std::allocator<void> > PreciseClock;

typedef boost::shared_ptr< ::rtkrcv::PreciseClock> PreciseClockPtr;
typedef boost::shared_ptr< ::rtkrcv::PreciseClock const> PreciseClockConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rtkrcv::PreciseClock_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rtkrcv::PreciseClock_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rtkrcv

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rtkrcv::PreciseClock_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rtkrcv::PreciseClock_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rtkrcv::PreciseClock_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1c8bd3bb2ae3e242d87bf2ed540c9e2d";
  }

  static const char* value(const  ::rtkrcv::PreciseClock_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1c8bd3bb2ae3e242ULL;
  static const uint64_t static_value2 = 0xd87bf2ed540c9e2dULL;
};

template<class ContainerAllocator>
struct DataType< ::rtkrcv::PreciseClock_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rtkrcv/PreciseClock";
  }

  static const char* value(const  ::rtkrcv::PreciseClock_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rtkrcv::PreciseClock_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# precise clock type\n\
\n\
time time               # time (GPST)\n\
int32 index             # clock index for multiple files\n\
float64[] clk           # satellite clock (s)\n\
float32[] std           # satellite clock std (s)\n\
";
  }

  static const char* value(const  ::rtkrcv::PreciseClock_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rtkrcv::PreciseClock_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.time);
    stream.next(m.index);
    stream.next(m.clk);
    stream.next(m.std);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PreciseClock_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rtkrcv::PreciseClock_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rtkrcv::PreciseClock_<ContainerAllocator> & v) 
  {
    s << indent << "time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time);
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "clk[]" << std::endl;
    for (size_t i = 0; i < v.clk.size(); ++i)
    {
      s << indent << "  clk[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.clk[i]);
    }
    s << indent << "std[]" << std::endl;
    for (size_t i = 0; i < v.std.size(); ++i)
    {
      s << indent << "  std[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.std[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // RTKRCV_MESSAGE_PRECISECLOCK_H

