/* Auto-generated by genmsg_cpp for file /home/asfandyar/gnss-master/rtkrcv/msg/stecd_t.msg */
#ifndef RTKRCV_MESSAGE_STECD_T_H
#define RTKRCV_MESSAGE_STECD_T_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace rtkrcv
{
template <class ContainerAllocator>
struct stecd_t_ {
  typedef stecd_t_<ContainerAllocator> Type;

  stecd_t_()
  : header()
  , sat(0)
  , slip(0)
  , iono(0.0)
  , rate(0.0)
  , rms(0.0)
  {
  }

  stecd_t_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , sat(0)
  , slip(0)
  , iono(0.0)
  , rate(0.0)
  , rms(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _sat_type;
  uint8_t sat;

  typedef uint8_t _slip_type;
  uint8_t slip;

  typedef float _iono_type;
  float iono;

  typedef float _rate_type;
  float rate;

  typedef float _rms_type;
  float rms;


  typedef boost::shared_ptr< ::rtkrcv::stecd_t_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rtkrcv::stecd_t_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct stecd_t
typedef  ::rtkrcv::stecd_t_<std::allocator<void> > stecd_t;

typedef boost::shared_ptr< ::rtkrcv::stecd_t> stecd_tPtr;
typedef boost::shared_ptr< ::rtkrcv::stecd_t const> stecd_tConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rtkrcv::stecd_t_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rtkrcv::stecd_t_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rtkrcv

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rtkrcv::stecd_t_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rtkrcv::stecd_t_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rtkrcv::stecd_t_<ContainerAllocator> > {
  static const char* value() 
  {
    return "95762bd9e503eecab8a0fa95f59b94b6";
  }

  static const char* value(const  ::rtkrcv::stecd_t_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x95762bd9e503eecaULL;
  static const uint64_t static_value2 = 0xb8a0fa95f59b94b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::rtkrcv::stecd_t_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rtkrcv/stecd_t";
  }

  static const char* value(const  ::rtkrcv::stecd_t_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rtkrcv::stecd_t_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# stec data type\n\
\n\
Header header           #time (GPST)\n\
uint8 sat               #satellite number\n\
uint8 slip              #slip flag\n\
float32 iono            #L1 ionosphere delay (m)\n\
float32 rate            #L1 ionosphere rate (m/s)\n\
float32 rms             #rms value (m)\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::rtkrcv::stecd_t_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::rtkrcv::stecd_t_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::rtkrcv::stecd_t_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rtkrcv::stecd_t_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.sat);
    stream.next(m.slip);
    stream.next(m.iono);
    stream.next(m.rate);
    stream.next(m.rms);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct stecd_t_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rtkrcv::stecd_t_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rtkrcv::stecd_t_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sat);
    s << indent << "slip: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.slip);
    s << indent << "iono: ";
    Printer<float>::stream(s, indent + "  ", v.iono);
    s << indent << "rate: ";
    Printer<float>::stream(s, indent + "  ", v.rate);
    s << indent << "rms: ";
    Printer<float>::stream(s, indent + "  ", v.rms);
  }
};


} // namespace message_operations
} // namespace ros

#endif // RTKRCV_MESSAGE_STECD_T_H

