"""autogenerated by genpy from rtkrcv/cbias.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class cbias(genpy.Message):
  _md5sum = "821a1a42ff1f270ad9a3e3a38516de2d"
  _type = "rtkrcv/cbias"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# code bias (0:p1-p2,1:p1-c1,2:p2-c2) (m)

float64 p1_p2
float64 p1_c1
float64 p2_c2
"""
  __slots__ = ['p1_p2','p1_c1','p2_c2']
  _slot_types = ['float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       p1_p2,p1_c1,p2_c2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(cbias, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.p1_p2 is None:
        self.p1_p2 = 0.
      if self.p1_c1 is None:
        self.p1_c1 = 0.
      if self.p2_c2 is None:
        self.p2_c2 = 0.
    else:
      self.p1_p2 = 0.
      self.p1_c1 = 0.
      self.p2_c2 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3d.pack(_x.p1_p2, _x.p1_c1, _x.p2_c2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.p1_p2, _x.p1_c1, _x.p2_c2,) = _struct_3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3d.pack(_x.p1_p2, _x.p1_c1, _x.p2_c2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.p1_p2, _x.p1_c1, _x.p2_c2,) = _struct_3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3d = struct.Struct("<3d")
