"""autogenerated by genpy from rtkrcv/SignalObservation.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SignalObservation(genpy.Message):
  _md5sum = "14a56f525e59be7564f63947c358c1cf"
  _type = "rtkrcv/SignalObservation"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Signal to noise ratio (0.25 dBHz)
uint8 snr
#Loss of lock indicator
uint8 lli
#Code indicator
uint8 sig_code
#Observation data carrier-phase (cycle)
float64 carrier_phase
#Observation data pseudorange (m)
float64 pseudorange
#Observation data doppler frequency (Hz)
float32 doppler

uint8 SIG_CODE_NONE = 0     # obs code: none or unknown
uint8 SIG_CODE_L1C  = 1     # obs code: L1C/A,E1C  (GPS,GLO,GAL,QZS,SBS)
uint8 SIG_CODE_L1P  = 2     # obs code: L1P        (GPS,GLO)
uint8 SIG_CODE_L1W  = 3     # obs code: L1 Z-track (GPS)
uint8 SIG_CODE_L1Y  = 4     # obs code: L1Y        (GPS)
uint8 SIG_CODE_L1M  = 5     # obs code: L1M        (GPS)
uint8 SIG_CODE_L1N  = 6     # obs code: L1codeless (GPS)
uint8 SIG_CODE_L1S  = 7     # obs code: L1C(D)     (GPS,QZS)
uint8 SIG_CODE_L1L  = 8     # obs code: L1C(P)     (GPS,QZS)
uint8 SIG_CODE_L1E  = 9     # obs code: L1-SAIF    (QZS)
uint8 SIG_CODE_L1A  = 10    # obs code: E1A        (GAL)
uint8 SIG_CODE_L1B  = 11    # obs code: E1B        (GAL)
uint8 SIG_CODE_L1X  = 12    # obs code: E1B+C,L1C(D+P) (GAL,QZS)
uint8 SIG_CODE_L1Z  = 13    # obs code: E1A+B+C    (GAL)
uint8 SIG_CODE_L2C  = 14    # obs code: L2C/A      (GPS,GLO)
uint8 SIG_CODE_L2D  = 15    # obs code: L2 L1C/A-(P2-P1) (GPS)
uint8 SIG_CODE_L2S  = 16    # obs code: L2C(M)     (GPS,QZS)
uint8 SIG_CODE_L2L  = 17    # obs code: L2C(L)     (GPS,QZS)
uint8 SIG_CODE_L2X  = 18    # obs code: L2C(M+L)   (GPS,QZS)
uint8 SIG_CODE_L2P  = 19    # obs code: L2P        (GPS,GLO)
uint8 SIG_CODE_L2W  = 20    # obs code: L2 Z-track (GPS)
uint8 SIG_CODE_L2Y  = 21    # obs code: L2Y        (GPS)
uint8 SIG_CODE_L2M  = 22    # obs code: L2M        (GPS)
uint8 SIG_CODE_L2N  = 23    # obs code: L2codeless (GPS)
uint8 SIG_CODE_L5I  = 24    # obs code: L5/E5aI    (GPS,GAL,QZS,SBS)
uint8 SIG_CODE_L5Q  = 25    # obs code: L5/E5aQ    (GPS,GAL,QZS,SBS)
uint8 SIG_CODE_L5X  = 26    # obs code: L5/E5aI+Q  (GPS,GAL,QZS,SBS)
uint8 SIG_CODE_L7I  = 27    # obs code: E5bI       (GAL)
uint8 SIG_CODE_L7Q  = 28    # obs code: E5bQ       (GAL)
uint8 SIG_CODE_L7X  = 29    # obs code: E5bI+Q     (GAL)
uint8 SIG_CODE_L6A  = 30    # obs code: E6A        (GAL)
uint8 SIG_CODE_L6B  = 31    # obs code: E6B        (GAL)
uint8 SIG_CODE_L6C  = 32    # obs code: E6C        (GAL)
uint8 SIG_CODE_L6X  = 33    # obs code: E6B+C      (GAL)
uint8 SIG_CODE_L6Z  = 34    # obs code: E6A+B+C    (GAL)
uint8 SIG_CODE_L6S  = 35    # obs code: LEX-S      (QZS)
uint8 SIG_CODE_L6L  = 36    # obs code: LEX-L      (QZS)
uint8 SIG_CODE_L8I  = 37    # obs code: E5(a+b)I   (GAL)
uint8 SIG_CODE_L8Q  = 38    # obs code: E5(a+b)Q   (GAL)
uint8 SIG_CODE_L8X  = 39    # obs code: E5(a+b)I+Q (GAL)
uint8 MAXSIGCODE   = 39    # max number of obs code
"""
  # Pseudo-constants
  SIG_CODE_NONE = 0
  SIG_CODE_L1C = 1
  SIG_CODE_L1P = 2
  SIG_CODE_L1W = 3
  SIG_CODE_L1Y = 4
  SIG_CODE_L1M = 5
  SIG_CODE_L1N = 6
  SIG_CODE_L1S = 7
  SIG_CODE_L1L = 8
  SIG_CODE_L1E = 9
  SIG_CODE_L1A = 10
  SIG_CODE_L1B = 11
  SIG_CODE_L1X = 12
  SIG_CODE_L1Z = 13
  SIG_CODE_L2C = 14
  SIG_CODE_L2D = 15
  SIG_CODE_L2S = 16
  SIG_CODE_L2L = 17
  SIG_CODE_L2X = 18
  SIG_CODE_L2P = 19
  SIG_CODE_L2W = 20
  SIG_CODE_L2Y = 21
  SIG_CODE_L2M = 22
  SIG_CODE_L2N = 23
  SIG_CODE_L5I = 24
  SIG_CODE_L5Q = 25
  SIG_CODE_L5X = 26
  SIG_CODE_L7I = 27
  SIG_CODE_L7Q = 28
  SIG_CODE_L7X = 29
  SIG_CODE_L6A = 30
  SIG_CODE_L6B = 31
  SIG_CODE_L6C = 32
  SIG_CODE_L6X = 33
  SIG_CODE_L6Z = 34
  SIG_CODE_L6S = 35
  SIG_CODE_L6L = 36
  SIG_CODE_L8I = 37
  SIG_CODE_L8Q = 38
  SIG_CODE_L8X = 39
  MAXSIGCODE = 39

  __slots__ = ['snr','lli','sig_code','carrier_phase','pseudorange','doppler']
  _slot_types = ['uint8','uint8','uint8','float64','float64','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       snr,lli,sig_code,carrier_phase,pseudorange,doppler

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SignalObservation, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.snr is None:
        self.snr = 0
      if self.lli is None:
        self.lli = 0
      if self.sig_code is None:
        self.sig_code = 0
      if self.carrier_phase is None:
        self.carrier_phase = 0.
      if self.pseudorange is None:
        self.pseudorange = 0.
      if self.doppler is None:
        self.doppler = 0.
    else:
      self.snr = 0
      self.lli = 0
      self.sig_code = 0
      self.carrier_phase = 0.
      self.pseudorange = 0.
      self.doppler = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3B2df.pack(_x.snr, _x.lli, _x.sig_code, _x.carrier_phase, _x.pseudorange, _x.doppler))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 23
      (_x.snr, _x.lli, _x.sig_code, _x.carrier_phase, _x.pseudorange, _x.doppler,) = _struct_3B2df.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3B2df.pack(_x.snr, _x.lli, _x.sig_code, _x.carrier_phase, _x.pseudorange, _x.doppler))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 23
      (_x.snr, _x.lli, _x.sig_code, _x.carrier_phase, _x.pseudorange, _x.doppler,) = _struct_3B2df.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3B2df = struct.Struct("<3B2df")
