(cl:in-package rtkrcv-msg)
(cl:export '(EPH-VAL
          EPH
          GEPH-VAL
          GEPH
          SEPH-VAL
          SEPH
          PEPH-VAL
          PEPH
          PCLK-VAL
          PCLK
          ALM-VAL
          ALM
          TEC-VAL
          TEC
          STEC-VAL
          STEC
          ERP-VAL
          ERP
          UTC_GPS-VAL
          UTC_GPS
          UTC_GLO-VAL
          UTC_GLO
          UTC_GAL-VAL
          UTC_GAL
          UTC_QZS-VAL
          UTC_QZS
          UTC_CMP-VAL
          UTC_CMP
          UTC_SBS-VAL
          UTC_SBS
          ION_GPS-VAL
          ION_GPS
          ION_GAL-VAL
          ION_GAL
          ION_QZS-VAL
          ION_QZS
          ION_CMP-VAL
          ION_CMP
          LEAPS-VAL
          LEAPS
          LAMCWL-VAL
          LAMCWL
          CODEBIAS-VAL
          CODEBIAS
          PCVS-VAL
          PCVS
          SBSSAT-VAL
          SBSSAT
          SBSION-VAL
          SBSION
          DGPS-VAL
          DGPS
          SSR-VAL
          SSR
          LEXEPH-VAL
          LEXEPH
          LEXION-VAL
          LEXION
          WLBIAS-VAL
          WLBIAS
          GLO_CPBIAS-VAL
          GLO_CPBIAS
          GLO_FCN-VAL
          GLO_FCN
))