(cl:in-package rtkrcv-msg)
(cl:export '(SAT-VAL
          SAT
          SVH-VAL
          SVH
          SVCONF-VAL
          SVCONF
          WEEK-VAL
          WEEK
          TOA-VAL
          TOA
          A-VAL
          A
          E-VAL
          E
          I0-VAL
          I0
          OMG0-VAL
          OMG0
          OMG-VAL
          OMG
          M0-VAL
          M0
          OMGD-VAL
          OMGD
          TOAS-VAL
          TOAS
          F0-VAL
          F0
          F1-VAL
          F1
))